# Generated by Django 3.0.8 on 2020-07-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=20, null=True)),
                ('LastName', models.CharField(blank=True, max_length=20, null=True)),
                ('UserName', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.CharField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
                ('ConPassword', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignupForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField(blank=True, max_length=20, null=True)),
                ('Email', models.TextField(blank=True, max_length=20, null=True)),
                ('Password', models.TextField(blank=True, max_length=20, null=True)),
                ('prim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebForm.registrationForm')),
            ],
        ),
    ]
